---
AnsibleBackupLoc: ""
ChefClientKey: "keys/admin.pem"
ChefNodeName: "admin"
ChefValidationKey: "keys/my_org-validator.pem"
CleanupFile: "/root/.cleanup"
ContainerName: "MOSE_DESTROYER_OF_WORLDS"
ImageName: "mose/chef-workstation"
PuppetBackupLoc: ""
RemoteHost: ""
SaltBackupLoc: ""
SSLCertPath: "data/mose.crt"
SSLKeyPath: "data/mose.key"
TargetChefServer: "chef-server"
TargetOrgName: "my_org"
TargetValidatorName: "my_org-validator"
UploadFilePath: "/root/.definitelynotevil"
